import json


def create_fastfetch(config_file):
    PRIMARY_COLOR = "#" + config_file["PRIMARY_COLOR"]
    SECONDARY_COLOR = "#" + config_file["SECONDARY_COLOR"]
    TERTIARY_COLOR = "#" + config_file["TERTIARY_COLOR"]
    TEXT_COLOR = "#" + config_file["TEXT_COLOR"]

    config_data = {
        "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/master/doc/json_schema.json",
        "display": {
            "brightColor": True,
            "color": {
                "keys": PRIMARY_COLOR,
                "output": TEXT_COLOR,
                "separator": TERTIARY_COLOR,
                "title": PRIMARY_COLOR,
            },
            "constants": [],
            "disableLinewrap": True,
            "duration": {"abbreviation": False, "spaceBeforeUnit": "default"},
            "fraction": {"ndigits": 2},
            "freq": {"ndigits": 2, "spaceBeforeUnit": "default"},
            "hideCursor": False,
            "key": {"paddingLeft": 0, "type": "both", "width": 12},
            "noBuffer": False,
            "percent": {
                "color": {"green": "32", "red": "91", "yellow": "93"},
                "ndigits": 0,
                "spaceBeforeUnit": "default",
                "type": ["num", "num-color"],
                "width": 0,
            },
            "pipe": False,
            "separator": "  ",
            "showErrors": False,
            "size": {
                "binaryPrefix": "iec",
                "maxPrefix": "YB",
                "ndigits": 2,
                "spaceBeforeUnit": "default",
            },
            "stat": False,
        },
        "general": {
            "detectVersion": True,
            "dsForceDrm": False,
            "playerName": "",
            "processingTimeout": 5000,
            "thread": True,
        },
        "logo": {
            "color": {
                "1": PRIMARY_COLOR,
                "2": SECONDARY_COLOR,
                "3": TERTIARY_COLOR,
                "4": "",
                "5": "",
                "6": "",
                "7": "",
                "8": "",
                "9": "",
            },
            "height": None,
            "padding": {"left": 0, "right": 4, "top": 0},
            "position": "left",
            "preserveAspectRatio": False,
            "printRemaining": True,
            "recache": False,
            "source": "",
            "type": "auto",
            "width": None,
        },
        "modules": [
            "break",
            {
                "format": " ┌───────────────── Hardware ─────────────────┐",
                "keyIcon": "",
                "outputColor": PRIMARY_COLOR,
                "type": "custom",
            },
            {
                "format": "",
                "key": " 󰪫 PC ",
                "keyColor": PRIMARY_COLOR,
                "keyIcon": "",
                "type": "custom",
            },
            {
                "format": "{1}",
                "key": "   ├ ",
                "keyColor": PRIMARY_COLOR,
                "keyIcon": "",
                "type": "board",
            },
            {
                "format": "{1}",
                "key": "   ├ ",
                "keyColor": PRIMARY_COLOR,
                "keyIcon": "",
                "type": "cpu",
            },
            {
                "format": "{2}",
                "key": "   ├󰢮 ",
                "keyColor": PRIMARY_COLOR,
                "keyIcon": "",
                "type": "gpu",
            },
            {
                "format": "{1} / {2} ({3})",
                "key": "   ├ ",
                "keyColor": PRIMARY_COLOR,
                "keyIcon": "",
                "type": "memory",
            },
            {
                "format": "{1} / {2} ({3}) [{9}]",
                "key": "   ├ ",
                "keyColor": PRIMARY_COLOR,
                "keyIcon": "",
                "type": "disk",
            },
            {
                "format": " └────────────────────────────────────────────┘",
                "keyIcon": "",
                "outputColor": PRIMARY_COLOR,
                "type": "custom",
            },
            "break",
            "break",
            {
                "format": " ┌───────────────── Software ─────────────────┐",
                "keyIcon": "",
                "outputColor": SECONDARY_COLOR,
                "type": "custom",
            },
            {
                "format": "{3}",
                "key": "  OS ",
                "keyColor": SECONDARY_COLOR,
                "keyIcon": "",
                "type": "os",
            },
            {
                "format": "{1} {2} | {4}",
                "key": "   ├󰒓 ",
                "keyColor": SECONDARY_COLOR,
                "keyIcon": "",
                "type": "kernel",
            },
            {
                "format": "{1} Packages",
                "key": "   ├󰏔 ",
                "keyColor": SECONDARY_COLOR,
                "keyIcon": "",
                "type": "packages",
            },
            "break",
            {"key": " 󰧨 WM ", "keyColor": SECONDARY_COLOR, "keyIcon": "", "type": "wm"},
            {"key": " 󰧨 DE ", "keyColor": SECONDARY_COLOR, "keyIcon": "", "type": "de"},
            {
                "format": "{1}: {6}",
                "key": "   ├ ",
                "keyColor": SECONDARY_COLOR,
                "keyIcon": "",
                "type": "terminal",
            },
            {
                "format": "{1}: {4}",
                "key": "   ├ ",
                "keyColor": SECONDARY_COLOR,
                "keyIcon": "",
                "type": "shell",
            },
            {
                "format": " └────────────────────────────────────────────┘",
                "keyIcon": "",
                "outputColor": SECONDARY_COLOR,
                "type": "custom",
            },
            "break",
            "break",
            {
                "format": " ┌─────────────────── MISC ───────────────────┐",
                "keyIcon": "",
                "outputColor": TERTIARY_COLOR,
                "type": "custom",
            },
            {
                "key": " TIME ",
                "keyColor": TERTIARY_COLOR,
                "keyIcon": "",
                "type": "custom",
            },
            {
                "format": "{1} Day(s), {2} Hours, {3} Minutes",
                "key": "   ├󰔛 ",
                "keyColor": TERTIARY_COLOR,
                "keyIcon": "",
                "type": "uptime",
            },
            {
                "key": "   ├󱦟 ",
                "keyColor": TERTIARY_COLOR,
                "keyIcon": "",
                "text": "birth_install=$(stat -c %W /); current=$(date +%s); days_difference=$(( (current - birth_install) / 86400 )); echo $days_difference days",
                "type": "command",
            },
            {
                "key": "   ├ ",
                "keyColor": TERTIARY_COLOR,
                "keyIcon": "",
                "text": "birth_install=$(stat -c %W /); echo $(date -d @$birth_install '+%d %b %Y')",
                "type": "command",
            },
            {
                "format": " └────────────────────────────────────────────┘",
                "keyIcon": "",
                "outputColor": TERTIARY_COLOR,
                "type": "custom",
            },
        ],
    }
    return json.dumps(config_data, indent=2)
