
# BLACK
color0                              #090618
color8                              #727169

# RED 
color1                              #c34043
color9                              #e82424

# GREEN
color2                              #76946a
color10                             #98bb6c

# YELLOW
color3                              #c0a36e
color11                             #e6c384

# BLUE
color4                              #7e9cd8
color12                             #7fb4ca

# MAGENTA
color5                              #957fb8
color13                             #938aa9

# CYAN
color6                              #6a9589
color14                             #7aa89f

# WHITE
color7                              #c8c093
color15                             #dcd7ba

foreground                          #dcd7ba
background                          #1a202b
selection_foreground                #c8c093
selection_background                #2d4f67

cursor                              #3BB8DB
cursor_text_color                   #dcd7ba
cursor_trail_color                  #6A7282

url_color                           #7aa89f
mark1_foreground                    black
mark1_background                    #3BB8DB
mark2_foreground                    black
mark2_background                    #6A7282
mark3_foreground                    black
mark3_background                    #C4B4FF

background_opacity                  0.8
background_blur                     1 
transparent_background_colors       red@0.5 #00ff00@0.3
dynamic_background_opacity          no
dim_opacity                         0.4

wayland_titlebar_color              background
