# Theme colors
rootcolor=0x3BB8DBff
bordercolor=0x6A7282FF
focuscolor=0x3BB8DBff
maximizescreencolor=0x3BB8DBff
urgentcolor=0x3BB8DBff
scratchpadcolor=0x3BB8DBff
globalcolor=0x3BB8DBff
overlaycolor=0x3BB8DBff

# Shadows
shadowscolor=0x0A0A0Aff

# Mouse
env=XCURSOR_SIZE,24
env=XCURSOR_THEME,Bibata-Modern-Ice
cursor_theme=Bibata-Modern-Ice
exec-once=gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'

# Other
env=GTK_THEME,Adwaita:dark
env=QT_STYLE_OVERRIDE,adwaita-dark
exec-once=gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once=gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
exec-once=swaybg -i ~/tekk-wallpapers/MesoAmerica/azTEKK.jpeg -m fill -c 000000
